# fly.toml app configuration file generated for eten-op-aw on 2023-05-10T00:25:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eten-op-aw"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[env]
  APP_ENV = "production"
  APP_LOCALE = "nl"
  APP_NAME = "Woensdagavond eten op AW"
  APP_TIMEZONE = "Europe/Amsterdam"
  DB_CONNECTION = "pgsql"
  DEBUG_EMAIL_BCC = "vincent@verbrugh.nl"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAILGUN_DOMAIN = "mg.amsterdamwindsurfing.nl"
  MAILGUN_ENDPOINT = "api.eu.mailgun.net"
  MAIL_FROM_ADDRESS = "no-reply@amsterdamwindsurfing.nl"
  MAIL_FROM_NAME = "Amsterdam Windsurfing"
  MAIL_MAILER = "mailgun"
  PRIMARY_REGION = "ams"

[processes]
  app = ""
  cron = "cron -f"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
