# fly.toml app configuration file generated for eten-op-aw on 2023-05-09T00:58:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eten-op-aw"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[env]
  APP_ENV = "production"
  APP_LOCALE = "nl"
  APP_NAME = "Woensdagavond eten op AW"
  APP_TIMEZONE = "Europe/Amsterdam"
  DB_CONNECTION = "pgsql"
  DEBUG_EMAILS = "true"
  DEBUG_EMAIL_BCC = "vincent@verbrugh.nl"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAILGUN_DOMAIN = "mg.amsterdamwindsurfing.nl"
  MAILGUN_ENDPOINT = "api.eu.mailgun.net"
  MAIL_FROM_ADDRESS = "no-reply@amsterdamwindsurfing.nl"
  MAIL_FROM_NAME = "Amsterdam Windsurfing"
  MAIL_MAILER = "mailgun"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  app = ""
  cron = "cron -f"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
